"""Stub file for moviepy module based on actual usage in Vine project."""

from typing import Any, Optional, Sequence, Tuple

# Video classes
class VideoClip:
    def with_duration(self, duration: float) -> "VideoClip": ...
    def with_position(self, pos: Tuple[float, float]) -> "VideoClip": ...
    def with_opacity(self, opacity: float) -> "VideoClip": ...
    def with_fps(self, fps: float) -> "VideoClip": ...
    def with_audio(self, audio: Any) -> "VideoClip": ...
    def resize(self, newsize: Tuple[int, int]) -> "VideoClip": ...
    def close(self) -> None: ...
    def set_duration(self, duration: float) -> "VideoClip": ...
    def write_videofile(self, filename: str, **kwargs: Any) -> None: ...

class ImageClip(VideoClip):
    def __init__(
        self,
        img: str,
        is_mask: bool = False,
        transparent: bool = True,
        fromalpha: bool = False,
        duration: Optional[float] = None,
    ) -> None: ...
    def with_duration(self, duration: float) -> "ImageClip": ...
    def with_position(self, pos: Tuple[float, float]) -> "ImageClip": ...
    def with_opacity(self, opacity: float) -> "ImageClip": ...
    def with_fps(self, fps: float) -> "ImageClip": ...
    def with_audio(self, audio: Any) -> "ImageClip": ...
    def resize(self, newsize: Tuple[int, int]) -> "ImageClip": ...

class TextClip(VideoClip):
    def __init__(
        self,
        text: str,
        font_size: int = 48,
        color: str = "white",
        method: str = "caption",
        size: Tuple[int, int] = (800, 600),
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def with_duration(self, duration: float) -> "TextClip": ...
    def with_position(self, pos: Tuple[float, float]) -> "TextClip": ...
    def with_opacity(self, opacity: float) -> "TextClip": ...
    def with_fps(self, fps: float) -> "TextClip": ...
    def with_audio(self, audio: Any) -> "TextClip": ...
    def resize(self, newsize: Tuple[int, int]) -> "TextClip": ...

class ColorClip(VideoClip):
    def __init__(
        self,
        size: Tuple[int, int],
        color: Tuple[int, int, int] = (0, 0, 0),
        duration: Optional[float] = None,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def with_duration(self, duration: float) -> "ColorClip": ...
    def with_position(self, pos: Tuple[float, float]) -> "ColorClip": ...
    def with_opacity(self, opacity: float) -> "ColorClip": ...
    def with_fps(self, fps: float) -> "ColorClip": ...
    def with_audio(self, audio: Any) -> "ColorClip": ...
    def resize(self, newsize: Tuple[int, int]) -> "ColorClip": ...

class VideoFileClip(VideoClip): ...

class CompositeVideoClip(VideoClip):
    def __init__(
        self,
        clips: Sequence[VideoClip],
        size: Optional[Tuple[int, int]] = None,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def with_duration(self, duration: float) -> "CompositeVideoClip": ...
    def with_position(self, pos: Tuple[float, float]) -> "CompositeVideoClip": ...
    def with_opacity(self, opacity: float) -> "CompositeVideoClip": ...
    def with_fps(self, fps: float) -> "CompositeVideoClip": ...
    def with_audio(self, audio: Any) -> "CompositeVideoClip": ...
    def resize(self, newsize: Tuple[int, int]) -> "CompositeVideoClip": ...

# Audio classes
class AudioClip:
    def __init__(
        self,
        make_frame: Any,
        duration: Optional[float] = None,
        *args: Any,
        **kwargs: Any,
    ) -> None: ...
    def with_duration(self, duration: float) -> "AudioClip": ...
    def with_volume_function(self, func: Any) -> "AudioClip": ...
    def with_volume_scaled(self, factor: float) -> "AudioClip": ...
    def with_effects(self, effects: Any) -> "AudioClip": ...
    def close(self) -> None: ...
    def set_duration(self, duration: float) -> "AudioClip": ...

class AudioFileClip(AudioClip):
    def with_duration(self, duration: float) -> "AudioFileClip": ...
    def with_volume_function(self, func: Any) -> "AudioFileClip": ...
    def with_volume_scaled(self, factor: float) -> "AudioFileClip": ...
    def with_effects(self, effects: Any) -> "AudioFileClip": ...

class CompositeAudioClip(AudioClip):
    def __init__(
        self, clips: Sequence[AudioClip], *args: Any, **kwargs: Any
    ) -> None: ...
    def with_duration(self, duration: float) -> "CompositeAudioClip": ...
    def with_volume_function(self, func: Any) -> "CompositeAudioClip": ...
    def with_volume_scaled(self, factor: float) -> "CompositeAudioClip": ...
    def with_effects(self, effects: Any) -> "CompositeAudioClip": ...

# Audio effects functions
def AudioFadeIn(
    clip: AudioClip, duration: float, *args: Any, **kwargs: Any
) -> AudioClip: ...
def AudioFadeOut(
    clip: AudioClip, duration: float, *args: Any, **kwargs: Any
) -> AudioClip: ...
def AudioNormalize(clip: AudioClip, *args: Any, **kwargs: Any) -> AudioClip: ...

# Main classes we use
__all__ = [
    "VideoClip",
    "VideoFileClip",
    "CompositeVideoClip",
    "ImageClip",
    "TextClip",
    "ColorClip",
    "AudioClip",
    "AudioFileClip",
    "CompositeAudioClip",
    "AudioFadeIn",
    "AudioFadeOut",
    "AudioNormalize",
]
